name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ''

      - name: Import Artifactory certificate
        run: |
          openssl s_client -connect artifactory.voya.net:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > artifactory.crt
          sudo keytool -importcert \
            -alias artifactory-voya \
            -file artifactory.crt \
            -keystore $JAVA_HOME/lib/security/cacerts \
            -storepass changeit \
            -noprompt

            
- name: Setup rootless Podman
        run: |
          # Method 1: Static binary (recommended)
          curl -LO https://github.com/containers/podman/releases/download/v4.9.3/podman-remote-static-linux_amd64.tar.gz
          tar -xzf podman-remote-static-*.tar.gz
          mkdir -p $HOME/bin
          mv podman-remote-static $HOME/bin/podman
          chmod +x $HOME/bin/podman
          echo "$HOME/bin" >> $GITHUB_PATH

          # Configure rootless
          export XDG_RUNTIME_DIR=/tmp/podman-run
          mkdir -p $XDG_RUNTIME_DIR

      - name: Test rootless container
        run: |
          podman --rootless run --rm registry.access.redhat.com/ubi8/ubi-minimal:latest echo "Success!"
