name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ''

      - name: Import Artifactory certificate
        run: |
          openssl s_client -connect artifactory.voya.net:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > artifactory.crt
          sudo keytool -importcert \
            -alias artifactory-voya \
            -file artifactory.crt \
            -keystore $JAVA_HOME/lib/security/cacerts \
            -storepass changeit \
            -noprompt

            
     - name: Setup rootless Podman
        run: |
          # Check architecture
          ARCH=$(uname -m)
          echo "Detected architecture: $ARCH"
          
          # Download correct binary
          if [[ "$ARCH" == "x86_64" ]]; then
            URL="https://github.com/containers/podman/releases/latest/download/podman-remote-static-linux_amd64.tar.gz"
          elif [[ "$ARCH" == "aarch64" ]]; then
            URL="https://github.com/containers/podman/releases/latest/download/podman-remote-static-linux_arm64.tar.gz"
          else
            echo "Unsupported architecture"
            exit 1
          fi
          
          curl -LO $URL
          tar -xzf podman-remote-static-*.tar.gz
          mkdir -p $HOME/bin
          mv podman-remote-static-* $HOME/bin/podman
          chmod +x $HOME/bin/podman
          echo "$HOME/bin" >> $GITHUB_PATH
          
          # Configure rootless
          export XDG_RUNTIME_DIR=/tmp/podman-run
          mkdir -p $XDG_RUNTIME_DIR
          echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >> $GITHUB_ENV
