name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Maven
        uses: actions/setup-maven@v3
        with: 
          maven-version: '3.8.8'
          cache: true


          =======

Current runner version: '2.325.0'
Runner name: 'github-arc-runners-5xwgs-runner-rzpll'
Machine name: 'github-arc-runners-5xwgs-runner-rzpll'
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action actions/setup-maven, repository not found
