name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ''

      - name: Import Artifactory certificate
        run: |
          openssl s_client -connect artifactory.voya.net:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > artifactory.crt
          sudo keytool -importcert \
            -alias artifactory-voya \
            -file artifactory.crt \
            -keystore $JAVA_HOME/lib/security/cacerts \
            -storepass changeit \
            -noprompt

            
 - name: Detect architecture
        id: arch
        run: |
          ARCH=$(uname -m)
          case $ARCH in
            x86_64)  echo "PODMAN_ARCH=amd64" >> $GITHUB_OUTPUT ;;
            aarch64) echo "PODMAN_ARCH=arm64" >> $GITHUB_OUTPUT ;;
            *)       echo "Unsupported architecture: $ARCH" && exit 1 ;;
          esac

      - name: Install Podman binary
        run: |
          # Create bin directory
          mkdir -p $HOME/bin
          
          # Download and extract correct binary
          curl -sSLo podman.tgz \
            "https://github.com/containers/podman/releases/latest/download/podman-remote-static-linux_${{ steps.arch.outputs.PODMAN_ARCH }}.tar.gz"
          tar -xzf podman.tgz --strip-components=1 -C $HOME/bin podman-remote-static
          mv $HOME/bin/podman-remote-static $HOME/bin/podman
          chmod +x $HOME/bin/podman
          echo "$HOME/bin" >> $GITHUB_PATH

          # Verify installation
          $HOME/bin/podman --version

      - name: Configure rootless environment
        run: |
          # Required directories
          export XDG_RUNTIME_DIR=/tmp/podman-$UID
          mkdir -p $XDG_RUNTIME_DIR
          echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >> $GITHUB_ENV
          
          # Storage configuration
          mkdir -p $HOME/.local/share/containers
          echo -e "[storage]\ndriver = \"vfs\"" > $HOME/.config/containers/storage.conf

      - name: Test Podman
        run: |
          podman --rootless info
          podman --rootless run --rm registry.access.redhat.com/ubi8/ubi-minimal:latest cat /etc/os-release
