name: Sonar test

on:
  push:
    branches: 
      - test_sonar

  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 for build
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Deploy custom settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/
          ls -la ~/.m2/
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Install Maven 3.8.8 (No Admin)
        run: |
          curl -L -o apache-maven-3.8.8-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
          mkdir -p ~/maven
          tar -xzf apache-maven-3.8.8-bin.tar.gz -C ~/maven
          echo "$HOME/maven/apache-maven-3.8.8/bin" >> $GITHUB_PATH
          $HOME/maven/apache-maven-3.8.8/bin/mvn --version
      - name: Write Artifactory CA cert from secret
        run: |
          echo "${{ secrets.ARTIFACTORY_CA_CRT }}" > artifactory-ca.crt
      - name: Create new Java truststore and import Artifactory CA cert
        run: |
          # Create a new empty Java truststore
          keytool -genkey -alias temp -keystore ./custom-cacerts -storepass changeit -keyalg RSA -dname "CN=temp" -validity 1
          keytool -delete -alias temp -keystore ./custom-cacerts -storepass changeit
          # Import the Artifactory CA certificate
          keytool -importcert -noprompt \
            -alias artifactory-ca \
            -file artifactory-ca.crt \
            -keystore ./custom-cacerts \
            -storepass changeit
          # Point all Java processes to use the new truststore
          echo "JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=$(pwd)/custom-cacerts -Djavax.net.ssl.trustStorePassword=changeit" >> $GITHUB_ENV
      
      - name: Build with Maven
        env:
          MAVEN_OPTS: "--add-modules=jdk.unsupported -Djavax.net.ssl.trustStore=${{ github.workspace }}/custom-cacerts -Djavax.net.ssl.trustStorePassword=changeit"
        run: |
          mvn -B clean package -DskipTests \
            -Dartifactory.resolve.contextUrl=https://artifactory.voya.net/artifactory \
            -Dartifactory.resolve.username=s700232 \
            -Dartifactory.resolve.password=Ingcc123! \
            -Dmaven.compiler.fork=true
 
      - name: Run SonarQube analysis
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
            -Dsonar.projectKey=Volo \
            -Dsonar.projectName=Volo \
            -Dsonar.host.url=https://sonarqube.voya.net/ \
            -Dsonar.login=sqa_8f629bcea9ef8f37f5a0efd32a37dda1233 \
            -Dsonar.java.jdkHome=$JAVA_HOME_11_X64 \  # Explicitly point to JDK 11
            -Dartifactory.resolve.username=s22222 \
            -Dartifactory.resolve.password=Igc12! \
            -s .github/maven/settings.xml


========

<?xml version="1.0" encoding="UTF-8"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.generate.project.parent</groupId>
	<artifactId>volo</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	<name>volo</name>
	<url>http://maven.apache.org</url>
	<properties>
 		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding> 
		<final.name>ivolo</final.name>
		<final.version>1.0.0</final.version>
		<target.dir>${project.basedir}/target/${project.artifactId}</target.dir>
		
		 <!-- Updated Java 17 properties -->
        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        
        <!-- Modern plugin versions -->
        <maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
        <sonar-maven-plugin.version>3.11.0.3922</sonar-maven-plugin.version>
		
		<!-- <sonar.projectKey>Volo</sonar.projectKey>
        <sonar.projectName>Volo</sonar.projectName> -->
		<sonar.skipSurefireTests>true</sonar.skipSurefireTests>
		<sonar.test.exclusions>**/*</sonar.test.exclusions>
	</properties>
	<!-- Add dependency management for tools.jar exclusion -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>sun.jdk</groupId>
                <artifactId>tools</artifactId>
                <version>1.8</version>
                <scope>system</scope>
                <systemPath>${java.home}/../lib/tools.jar</systemPath>
                <optional>true</optional>
            </dependency>
            
            <!-- Add Jakarta EE dependencies for Java 17 -->
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>4.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>4.0.3</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
	<modules>
		<module>voloJAR</module>
		<module>voloWAR</module>
	</modules>
	<dependencies>
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1</version>
		</dependency>
		<dependency>
			<groupId>asm</groupId>
			<artifactId>asm</artifactId>
			<version>3.3</version>
		</dependency>
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>2.2</version>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.9.4</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
                        <artifactId>commons-collections4</artifactId>
                        <version>4.4</version>
		</dependency>
		<dependency>
			<groupId>commons-digester</groupId>
			<artifactId>commons-digester</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>commons-discovery</groupId>
			<artifactId>commons-discovery</artifactId>
			<version>0.5</version>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.6</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.22</version>
		</dependency>
		<dependency>
                       <groupId>com.google.guava</groupId>
                       <artifactId>guava</artifactId>
                       <version>29.0-jre</version>
               </dependency>
		<dependency>
			<groupId>com.itextpdf</groupId>
			<artifactId>itextpdf</artifactId>
			<version>5.5.13.1</version>
		</dependency>
		
		<!-- Added jtds driver patched version dependency for DIME changes -->
		<!-- <dependency>
			<groupId>net.sourceforge.jtds</groupId>
			<artifactId>jtds</artifactId>
			<version>1.2.7</version>
		</dependency> -->
		<!-- <dependency> 
			<groupId>net.sourceforge.jtds</groupId> 
			<artifactId>jtds</artifactId> 
			<version>1.3.1-patch-20190523</version> 
		</dependency> -->
		<!-- https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc -->
		<dependency>
		    <groupId>com.microsoft.sqlserver</groupId>
		    <artifactId>mssql-jdbc</artifactId>
		    <version>7.4.1.jre8</version>
		</dependency>
		
		<dependency>
			<groupId>log4j</groupId>
                        <artifactId>log4j</artifactId>
                        <version>1.2.17</version>
		</dependency>
		<!--dependency>
			<groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-core</artifactId>
                        <version>2.13.3</version>
          </dependency>              
         <dependency>
	        <groupId>org.apache.logging.log4j</groupId>
		        <artifactId>log4j-api</artifactId>
		        <version>2.13.3</version>
                
		</dependency -->
		<!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-core</artifactId>
		    <version>2.16.0</version>
		</dependency>
				<!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-api</artifactId>
		    <version>2.16.0</version>
		</dependency>
		
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.1</version>
		</dependency>
		<dependency>
                       <groupId>ognl</groupId>
                       <artifactId>ognl</artifactId>
                       <version>3.0.19</version>
                 </dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>4.1.2</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.struts</groupId>
			<artifactId>struts2-core</artifactId>
			<version>2.5.33</version>
		</dependency>
		<!-- <dependency>
			<groupId>org.apache.struts</groupId>
			<artifactId>struts2-dojo-plugin</artifactId>
			<version>2.5.20</version>
		</dependency> -->
		
		 <dependency>
				<groupId>com.jgeppert.struts2.jquery</groupId>
				<artifactId>struts2-jquery-plugin</artifactId>
				<version>4.0.3</version>
			</dependency> 
		<dependency>
			<groupId>org.apache.struts</groupId>
			<artifactId>struts2-json-plugin</artifactId>
			<version>2.5.33</version>
		</dependency>
		<dependency>
			<groupId>org.apache.struts</groupId>
			<artifactId>struts2-tiles-plugin</artifactId>
			<version>2.5.33</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tiles</groupId>
			<artifactId>tiles-api</artifactId>
			<version>3.0.8</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tiles</groupId>
			<artifactId>tiles-core</artifactId>
			<version>3.0.8</version>
			<!-- 2.5 updation -->
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>jcl-over-slf4j</artifactId>
				</exclusion>
			</exclusions>
			<!-- 2.5 updation -->
			
		</dependency>
		<dependency>
			<groupId>org.apache.tiles</groupId>
			<artifactId>tiles-jsp</artifactId>
			<version>3.0.8</version>
		</dependency>
		<!-- <dependency>
			<groupId>com.opensymphony</groupId>
			<artifactId>xwork</artifactId>
			<version>2.1.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.struts.xwork</groupId>
			<artifactId>xwork-core</artifactId>
			<version>2.3.12</version>
		</dependency> -->
		<dependency>
			<groupId>Voya</groupId>
			<artifactId>ServiceIDRem</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-business</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-cache</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-collections</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-common-annotations</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-common-services</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-dbutil</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-factory</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-genex-ws-stubs</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-jaas</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-ldap</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-logging</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-logging-base</artifactId>
			<version>44.0-SNAPSHOT</version>
			
		</dependency>
		<!-- <dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-logging-struts</artifactId>
			<version>44.0-SNAPSHOT</version>
			2.5 updation
			<exclusions>
				<exclusion>
					<groupId>org.apache.struts</groupId>
					<artifactId>struts-core</artifactId>
				</exclusion>
			</exclusions>
			2.5 updation
		</dependency> -->
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-proxy</artifactId>
			<version>44.0-SNAPSHOT</version>
			
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-security</artifactId>
			<version>44.0-SNAPSHOT</version>
			
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-services</artifactId>
			<version>44.0-SNAPSHOT</version>
			
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-setit</artifactId>
			<version>44.0-SNAPSHOT</version>
			
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-setit-ws-stubs</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-spnego</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-sso</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-sso-ws-stubs</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<!-- <dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-struts-base</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency> -->
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-struts2-base</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-txmgr</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-ucp</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-util</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-web-utils</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-ws-utils</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>genex-ext</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>cs-projects</groupId>
			<artifactId>cs-web-common</artifactId>
			<version>44.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.12.0.GA</version>
		</dependency>
		<dependency>
                       <groupId>com.jcraft</groupId>
                       <artifactId>jsch</artifactId>
                       <version>0.1.55</version>
                </dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jsp-api</artifactId>
			<version>2.2</version>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>1.8.6</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>3.0</version>
		</dependency>
		<dependency>
			<groupId>org.syslog</groupId>
			<artifactId>syslog</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging-api</artifactId>
			<version>1.1</version>
		</dependency>
		<dependency>
			<groupId>net.sourceforge.findbugs</groupId>
			<artifactId>findbugs-annotations</artifactId>
			<version>1.2.1</version>
		</dependency>
	</dependencies>
<build>
        <pluginManagement>
            <plugins>
                <!-- Updated compiler plugin for Java 17 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                        <compilerArgs>
                            <arg>--add-modules=jdk.unsupported</arg>
                            <arg>-Xlint:unchecked</arg>
                        </compilerArgs>
                        <showWarnings>true</showWarnings>
                        <showDeprecation>true</showDeprecation>
                    </configuration>
                </plugin>
                
                <!-- Updated SonarQube plugin -->
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${sonar-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>verify</phase>
                            <goals>
                                <goal>sonar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                
                <!-- Other existing plugins... -->
            </plugins>
        </pluginManagement>
        
        <plugins>
            <!-- Ensure compiler plugin is active -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>

=======================


Error:  Failed to execute goal on project voloJAR: Could not resolve dependencies for project com.generate.project.module:voloJAR:jar:1.0.0: Could not find artifact sun.jdk:tools:jar:1.8 at specified path /home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/17.0.15-6/x64/../lib/tools.jar -> [Help 1]
