name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ''

      - name: Import Artifactory certificate
        run: |
          openssl s_client -connect artifactory.voya.net:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > artifactory.crt
          sudo keytool -importcert \
            -alias artifactory-voya \
            -file artifactory.crt \
            -keystore $JAVA_HOME/lib/security/cacerts \
            -storepass changeit \
            -noprompt

            
/home/runner/_work/_temp/224e4bf2-d4ac-4af0-a632-855280e2a822.sh: line 13: /home/runner/bin/podman: cannot execute binary file: Exec format error
