name: Sonar test

on:
  push:
    branches: 
      - test_sonar
  workflow_dispatch: 

jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 for build
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Deploy custom settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/
          ls -la ~/.m2/

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Install Maven
        run: |
          curl -L -o apache-maven-3.8.8-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
          mkdir -p ~/maven
          tar -xzf apache-maven-3.8.8-bin.tar.gz -C ~/maven
          echo "$HOME/maven/apache-maven-3.8.8/bin" >> $GITHUB_PATH
          $HOME/maven/apache-maven-3.8.8/bin/mvn --version

      - name: SSL Configuration
        run: |
          echo "${{ secrets.ARTIFACTORY_CA_CRT }}" > artifactory-ca.crt
          keytool -genkey -alias temp -keystore ./custom-cacerts -storepass changeit -keyalg RSA -dname "CN=temp" -validity 1
          keytool -delete -alias temp -keystore ./custom-cacerts -storepass changeit
          keytool -importcert -noprompt \
            -alias artifactory-ca \
            -file artifactory-ca.crt \
            -keystore ./custom-cacerts \
            -storepass changeit
          echo "JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=$(pwd)/custom-cacerts -Djavax.net.ssl.trustStorePassword=changeit" >> $GITHUB_ENV
      
      - name: Build with Maven
        env:
          MAVEN_OPTS: "--add-modules=java.se,jdk.unsupported -Djavax.net.ssl.trustStore=${{ github.workspace }}/custom-cacerts -Djavax.net.ssl.trustStorePassword=changeit"
        run: |
          mvn -B clean package -DskipTests \
            -Dartifactory.resolve.contextUrl=https://artifactory.voya.net/artifactory \
            -Dartifactory.resolve.username=${{ secrets.ARTIFACTORY_USERNAME }} \
            -Dartifactory.resolve.password=${{ secrets.ARTIFACTORY_PASSWORD }} \
            -Pjava17 \
            -Dmaven.compiler.fork=true
            
      - name: Run SonarQube analysis
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
            -Dsonar.projectKey=Volo \
            -Dsonar.projectName=Volo \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.jdkHome=$JAVA_HOME_11_X64 \
            -s .github/maven/settings.xml
