name: Use Podman via Container

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  podman-via-container:
    runs-on: openshift-arc-runner
    
    container:
      image: quay.io/podman/stable:latest
      options: --device /dev/fuse --group-add keep-groups

    steps:
    - name: Test Podman in Podman
      run: |
        podman --version
        podman info
        
        # Test rootless operation
        podman run --rm --user 1000 registry.access.redhat.com/ubi8/ubi-minimal:latest whoami
        
        # Test storage
        podman pull registry.access.redhat.com/ubi8/ubi-minimal:latest
        podman images
