name: Build EDT-HS-Microsites

on:
  workflow_dispatch:  # Allows manual triggering
  # push:
  #   branches: [ main ]  # Uncomment to trigger on pushes to main

jobs:
  build:
    runs-on: djax123_win_runner  # Your self-hosted runner
    
    env:
      buildConfiguration: 'Release'
      buildPlatform: 'x64'
      solutionName: 'EDT-HS-Microsites/EDT-HS-Microsites.sln'
      visualStudioVersion: '14.0'
      # buildNumber will be set in the steps

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set build number
      id: set-build-number
      run: |
        $date = Get-Date -Format "yyyyMMdd.HHmmss"
        echo "build_number=1.0.$date" >> $env:GITHUB_OUTPUT
      shell: pwsh

    # Restore NuGet packages
    - name: NuGet restore
      run: nuget restore $env:solutionName
      shell: cmd

    # Main build
    - name: MSBuild CompileAllProject
      run: |
        msbuild EDT-HS-Microsites.build `
          /t:CompileAllProject `
          /p:VisualStudioVersion=$env:visualStudioVersion `
          /p:DeployOnBuild=True `
          /p:DeployDefaultTarget="WebPublish" `
          /p:WebPublishMethod="FileSystem" `
          /p:DeleteExistingFiles=True `
          /p:publishUrl=./dist/Root/Deploy `
          /p:GenerateProjectSpecificOutputFolder=true `
          /p:OutputPath=${{ github.workspace }}\dist `
          /p:Platform=$env:buildPlatform `
          /p:Configuration=$env:buildConfiguration

    # Artifacts packaging
    - name: MSBuild artifacts
      run: |
        msbuild artifacts.msbuild `
          /t:All `
          /p:BRANCH=${{ github.ref_name }} `
          /p:BUILD_NUMBER=${{ steps.set-build-number.outputs.build_number }} `
          /p:JOB_NAME="${{ github.workflow }}" `
          /p:ArchiveDirectory="${{ github.workspace }}\dist\_PublishedWebsites" `
          /p:SevenZipPath="C:\Program Files\7-Zip\7z.exe"

    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/target
