name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ''
          # cache: maven
      - name: Deploy custom settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/
          ls -la ~/.m2/
      - name: Install Maven 3.8.8 (No Admin)
        run: |
          # Download Maven using curl 
          curl -L -o apache-maven-3.8.8-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
          
          # Extract and set up
          mkdir -p ~/maven
          tar -xzf apache-maven-3.8.8-bin.tar.gz -C ~/maven
          echo "$HOME/maven/apache-maven-3.8.8/bin" >> $GITHUB_PATH
          
          # Verify installation
          $HOME/maven/apache-maven-3.8.8/bin/mvn --version


          
      - name: Build with Maven
        run: mvn clean package -DskipTests

  

configuration>
							<url>${artifactory.resolve.contextUrl}/maven-trusted/com/voya/descriptor/1.0/descriptor-1.0-envconfig.xml</url>

