name: Build and Package - Maven testing

on:
  push:
    branches: 
      - Test_Volo
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: github-arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ''

      - name: Import Artifactory certificate
        run: |
          openssl s_client -connect artifactory.voya.net:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > artifactory.crt
          sudo keytool -importcert \
            -alias artifactory-voya \
            -file artifactory.crt \
            -keystore $JAVA_HOME/lib/security/cacerts \
            -storepass changeit \
            -noprompt

            
Build container for action use: '/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1/Dockerfile'.
  /usr/bin/docker build -t f7306c:e037235cd06746708f9a1a834c3c8ff2 -f "/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1/Dockerfile" "/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1"
  ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Warning: Docker build failed with exit code 1, back off 8.554 seconds before retry.
  /usr/bin/docker build -t f7306c:e037235cd06746708f9a1a834c3c8ff2 -f "/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1/Dockerfile" "/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1"
  ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Warning: Docker build failed with exit code 1, back off 8.491 seconds before retry.
  /usr/bin/docker build -t f7306c:e037235cd06746708f9a1a834c3c8ff2 -f "/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1/Dockerfile" "/home/runner/_work/_actions/SonarSource/sonarqube-scan-action/v1"
  ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: Docker build failed with exit code 1
