trigger: none
# - main  # or your main branch name
pool:
  name: Windows_Servers
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'x64'
  solutionName: 'EDT-HS-Microsites/EDT-HS-Microsites.sln'
  visualStudioVersion: '14.0'
  buildNumber: $(Build.BuildNumber)  # Azure DevOps build number

# pool:
#   vmImage: 'windows-latest'  # or 'windows-2019' for VS2019

steps:
# Install NuGet
- task: NuGetToolInstaller@1

# Restore packages (replicates BeforeBuild target)
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solutionName)'
    feedsToUse: 'select'

# Run the main build (replicates CompileAllProject target)
- task: MSBuild@1
  inputs:
    solution: 'EDT-HS-Microsites.build'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:CompileAllProject /p:VisualStudioVersion=$(visualStudioVersion) /p:DeployOnBuild=True /p:DeployDefaultTarget="WebPublish" /p:WebPublishMethod="FileSystem" /p:DeleteExistingFiles=True /p:publishUrl=./dist/Root/Deploy /p:GenerateProjectSpecificOutputFolder=true /p:OutputPath=$(Build.SourcesDirectory)\dist'
    msbuildArchitecture: 'x64'

# Install 7zip (required for artifacts.msbuild)
# - powershell: |
#     choco install 7zip -y --force
#   displayName: 'Install 7zip'
#   condition: eq(variables['Agent.OS'], 'Windows_NT')

# Run artifacts packaging (replicates artifacts.msbuild)
- task: MSBuild@1
  inputs:
    solution: 'artifacts.msbuild'
    msbuildArguments: '/t:All /p:BRANCH=$(Build.SourceBranchName) /p:BUILD_NUMBER=$(Build.BuildNumber) /p:JOB_NAME="$(Build.DefinitionName)" /p:ArchiveDirectory="$(Build.SourcesDirectory)\dist\_PublishedWebsites" /p:SevenZipPath="C:\Program Files\7-Zip\7z.exe"'
    msbuildArchitecture: 'x64'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
